---
- name: Install required packages (3.11)
  yum:
    name:
      - openshift-ansible
      - vim-enhanced
      - git
      - wget
      - sshpass
      - ansible
      - docker
      - tree
    state: present
  become: yes

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Put student inventory in proper spot
  copy:
    src: ./{{ec2_name_prefix}}/{{ username }}-inventory.txt
    dest: /etc/ansible/hosts
  when: username in inventory_hostname

- name: Install EPEL repo so we can install PIP
  yum:
    name:  "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: install PIP
  yum:
    name: python-pip
    state: present

- name: install docker-py requirements
  pip:
    name: docker-py
    state: present
    extra_args: --trusted-host pypi.org --trusted-host files.pythonhosted.org

- name: pull the lab guide image
  docker_image:
    name: quay.io/jduncan/operator-workshop-lab-guide-better-together
    state: present

- name: get public IP for control node
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    return_content: yes
  register: pub_ip

- name: create the environment file for doxcker
  template:
    src: env.list.j2
    dest: /tmp/env.list

- name: start the lab guide container
  docker_container:
    name: lab_guide
    image: quay.io/jduncan/operator-workshop-lab-guide-better-together
    env_file: /tmp/env.list
    ports:
      - "8080:8080"
    restart_policy: always
