---
- name: Install required packages (3.9)
  yum:
    name:
      - atomic-openshift-utils
      - vim-enhanced
      - git
      - wget
      - sshpass
      - ansible
    state: present
  when: (openshift_version | string) == "3.9"
  become: yes

- name: Install required packages (3.10)
  yum:
    name:
      - openshift-ansible
      - vim-enhanced
      - git
      - wget
      - sshpass
      - ansible
    state: present
  when: (openshift_version | string) == "3.10"
  become: yes

- name: Install required packages (3.11)
  yum:
    name:
      - openshift-ansible
      - vim-enhanced
      - git
      - wget
      - sshpass
      - ansible
    state: present
  when: (openshift_version | string) == "3.11"
  become: yes

- name: Put student inventory in proper spot
  copy:
    src: ./{{ec2_name_prefix}}/{{ username }}-inventory.txt
    dest: /etc/ansible/hosts
  when: username in inventory_hostname
