---
- name: Include platform-specific tasks
  include_tasks: "{{ provision_type }}.yml"

- name: Include distro-specific variables
  include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: Include distro-specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

# There is a current bug with DNSmasq causing things to fail during an
# OpenShift install. Installing/upgrading and then rebooting the nodes is
# the current workaround.
- name: Install/upgrade dnsmasq
  yum:
    name: dnsmasq
    state: latest
  become: yes

- name: Install openvswitch package
  yum:
    name: openvswitch
    state: latest
  become: yes

- name: Update all packages
  yum:
    name: "*"
    state: latest
  retries: 3  # This seems to fail sometimes, so lets retry before failing everything
  until: update_all_packages.rc == 0
  register: update_all_packages
  become: yes

- name: Reboot host
  shell: sleep 30 && shutdown -r now
  async: 30
  poll: 0
  ignore_errors: yes
  become: yes

- name: Wait for nodes to boot
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 30
    timeout: 300
    search_regex: OpenSSH
  delegate_to: localhost
