---
# - block:
#   - import_tasks: certs.yml
#
#

- name: Run OpenShift prerequisites
  command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  become: no
  tags: openshift_deploy_cluster

- name: Run OpenShift installer (this will take a while!)
  command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
  become: no
  tags: openshift_deploy_cluster
