---
# - block:
#   - import_tasks: certs.yml
#
#
- name: copy generated AWS key to bastion host
  copy:
    src: "{{ playbook_dir }}/{{ cluster_name }}/{{ cluster_name }}-private.pem"
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0400

- name: copy ssh config to the bastion host
  template:
    src: ssh_config
    dest: "/home/{{ openshift_ec2_user }}/.ssh/config"
    owner: "{{ openshift_ec2_user }}"
    group: "{{ openshift_ec2_user }}"
    mode: 0400

- name: copy ansible config to the bastion host
  template:
    src: ansible_config
    dest: "/home/{{ openshift_ec2_user }}/.ansible/config"
    owner: "{{ openshift_ec2_user }}"
    group: "{{ openshift_ec2_user }}"
    mode: 0600

- name: Run OpenShift prerequisites
  command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  become: no
  tags: openshift_deploy_cluster

# - name: Run OpenShift installer (this will take a while!)
#   command: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
#   become: no
#   tags: openshift_deploy_cluster
