- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
      # Please read this, if you try to delete this task
      # https://github.com/network-automation/linklight/issues/21
    - name: make sure we are running correct Ansible Version
      assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 6

    - name: run role to check if local environment setup will work with AWS
      include_role:
        name: aws_check_setup

    - name: make sure we are not running with TESTWORKSHOP as the name so no overlap
      assert:
        that:
          - ec2_name_prefix != "TESTWORKSHOP"

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    teardown: false
  roles:
    - manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes"
  become: yes
  gather_facts: no
  roles:
    - connectivity_test

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  roles:
    - user_accounts
    - common
    - common_ocp

- name: CONFIGURE CONTROL NODE
  hosts: control_nodes
  become: yes
  roles:
    - control_node_ocp
    - ocp_deploy
  tags: control_node

- name: Configure Users for OpenShift cluster
  hosts: master_nodes
  become: yes
  roles:
    - addusers_ocp

- name: Configure Databae nodes for OpenShift workshop
  hosts: database_nodes
  become: yes
  roles:
    - ocp_workshop_db

- name: Setup Amazon S3 Website for Student Login
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - { role: aws_workshop_login_page, when: create_login_page is defined and create_login_page }
