---
- name: Ensure git is installed
  yum:
    name: git
    state: present
    
- name: Check out CI/CD demo for use in workshop
  git:
    repo: 'https://github.com/siamaksade/openshift-cd-demo.git'
    dest: /root/cicd-demo

- name: Create htpasswd file
  copy:
    content: ""
    dest: /etc/origin/master/htpasswd
    force: no

- name: Create users
  command: htpasswd -b /etc/origin/master/htpasswd '{{ item.username }}' '{{ item.password }}'
  with_items: "{{ openshift_users }}"
  become: yes

- name: Create admin users
  command: oc adm policy add-cluster-role-to-user cluster-admin '{{ item.username }}'
  with_items: "{{ openshift_users }}"
  when: item.admin is defined and item.admin == True
